#DB config
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: C##SECURITY
    password: SECURITY

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml


